---
- name: restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: reload ufw
  community.general.ufw:
    state: reloaded
